#!/bin/bash

set -ex

clean_exit() {
        exit 0
}

trap clean_exit ERR

# The locale for the images that will be downloaded
locale=en-GB

# Path that downloaded Spotlight images will be saved to
img_path=$HOME/.cache/spot-the-gnome

# Images in the specified directory above will be deleted after this number of days
retention_days=30

# Check that the directory specified exists, and if not, make it
mkdir -p "${img_path}"

# Use cURL to make a request to the Bing API and get the request JSON
req_json=$(curl -s -G "https://www.bing.com/HPImageArchive.aspx" \
        -d format=js \
        -d idx=0 \
        -d n=1 \
        -d mkt=$locale
)

image_url=$(echo "$req_json" | jq -r '.images[0].url')
image_title=$(echo "$req_json" | jq -r '.images[0].title')

#Specify the image name
img_name="${img_path}/${image_title}.jpeg"

# Exit if the image already exists
if [ -f "${img_name}" ]; then
        exit 0
fi

# Download the image
curl -s "https://bing.com${image_url}" -o "${img_name}"

# Set the wallpaper for the desktop
gsettings set org.gnome.desktop.background picture-uri "file://${img_name}"
gsettings set org.gnome.desktop.background picture-uri-dark "file://${img_name}"

# Delete any images that are old enough
if [ $retention_days -gt 0 ]; then
        for name in "${img_path}"/*.jpeg; do
                if [ $(( ($(date +%s) - $(stat -c %Y "${name}")) / 60 / 60 / 24 )) -ge $retention_days ]; then
                        gio trash "${name}"
                fi
        done
fi
